// <auto-generated />
using ClothingWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClothingWeb.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251016100124_SeedCategoryTable")]
    partial class SeedCategoryTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClothingWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Wedding"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Traditional"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Sports Wear"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Summer Wear"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Winter Wear"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Baby Wear"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
